version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "8080:8080"
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - FLASK_APP=application.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=8080

